FROM elasticsearch:1.7.1

RUN /usr/share/elasticsearch/bin/plugin -install langdetect -url http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-langdetect/1.4.4.2/elasticsearch-langdetect-1.4.4.2-plugin.zip
